<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <!-- C# 9 because of Unity -->
        <LangVersion>9.0</LangVersion>
        <!-- Can be removed when upgrading from .NET 2.1 (in Unity I guess) -->
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="MongoDB.Bson" />
        <PackageReference Include="MongoDB.Driver" />
    </ItemGroup>
</Project>